spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
server:
  port: 8080
